services:
  nginx:
    build:
      context: ./infra/nginx
      dockerfile: Dockerfile
    container_name: nginx-gateway
    ports:
      - "8000:80"
    depends_on:
      - user
      - tenant
      - resource
      - booking
    networks:
      - backend_net

  user:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    expose:
      - "8000"
    container_name: user
    environment:
      - DATABASE_URL=postgresql://user:password@db_user:5432/userdb
      - REDIS_URL=redis://redis:6379
      - TENANT_SERVICE_URL=http://tenant:8000
      - SECRET_KEY=ca76563c37354029ac4e02d96427a444dce2f9401ddb366afee9e70219885ef44add634887d2956d1cabaec071d4b78d61d4b84bfae6aec80213f0a27d350864
      - JWT_ALGORITHM=HS512
      - ACCESS_TOKEN_EXPIRE_HOURS=24
      - CORS_ORIGINS=http://localhost:3000,https://chronos-webdev.vercel.app,https://chronos-git-fix-adjust-applicat-3fca67-aildsonsh-1784s-projects.vercel.app,https://chronos-i1cnx4csg-aildsonsh-1784s-projects.vercel.app
    depends_on:
      db_user:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend_net
    command: ["/bin/sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  tenant:
    build:
      context: .
      dockerfile: services/tenant/Dockerfile
    expose:
      - "8000"
    container_name: tenant
    hostname: tenant
    environment:
      - DATABASE_URL=postgresql://user:password@db_tenant:5432/tenantdb
      - SECRET_KEY=ca76563c37354029ac4e02d96427a444dce2f9401ddb366afee9e70219885ef44add634887d2956d1cabaec071d4b78d61d4b84bfae6aec80213f0a27d350864
      - JWT_ALGORITHM=HS512
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=http://localhost:3000,https://chronos-webdev.vercel.app,https://chronos-git-fix-adjust-applicat-3fca67-aildsonsh-1784s-projects.vercel.app,https://chronos-i1cnx4csg-aildsonsh-1784s-projects.vercel.app
    depends_on:
      db_tenant:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend_net
    command: ["/bin/sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  resource:
    build:
      context: .
      dockerfile: services/resource/Dockerfile
    expose:
      - "8000"
    container_name: resource
    environment:
      - DATABASE_URL=postgresql://user:password@db_resource:5432/resourcedb
      - REDIS_URL=redis://redis:6379
      - TENANT_SERVICE_URL=http://tenant:8000
      - BOOKING_SERVICE_URL=http://booking:8000
      - SECRET_KEY=ca76563c37354029ac4e02d96427a444dce2f9401ddb366afee9e70219885ef44add634887d2956d1cabaec071d4b78d61d4b84bfae6aec80213f0a27d350864
      - JWT_ALGORITHM=HS512
      - CORS_ORIGINS=http://localhost:3000,https://chronos-webdev.vercel.app,https://chronos-git-fix-adjust-applicat-3fca67-aildsonsh-1784s-projects.vercel.app,https://chronos-i1cnx4csg-aildsonsh-1784s-projects.vercel.app
    depends_on:
      db_resource:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend_net
    command: ["/bin/sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  booking:
    build:
      context: .
      dockerfile: services/booking/Dockerfile
    expose:
      - "8000"
    container_name: booking
    environment:
      - DATABASE_URL=postgresql://user:password@db_booking:5432/bookingdb
      - REDIS_URL=redis://redis:6379
      - TENANT_SERVICE_URL=http://tenant:8000
      - RESOURCE_SERVICE_URL=http://resource:8000
      - USER_SERVICE_URL=http://user:8000
      - SECRET_KEY=ca76563c37354029ac4e02d96427a444dce2f9401ddb366afee9e70219885ef44add634887d2956d1cabaec071d4b78d61d4b84bfae6aec80213f0a27d350864
      - JWT_ALGORITHM=HS512
      - CORS_ORIGINS=http://localhost:3000,https://chronos-webdev.vercel.app,https://chronos-git-fix-adjust-applicat-3fca67-aildsonsh-1784s-projects.vercel.app,https://chronos-i1cnx4csg-aildsonsh-1784s-projects.vercel.app
    depends_on:
      db_booking:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend_net
    command: ["/bin/sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  db_user:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d userdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - backend_net

  db_tenant:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tenantdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tenantdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - backend_net

  db_resource:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resourcedb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d resourcedb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - backend_net

  db_booking:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookingdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bookingdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - backend_net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge
